# Generated by Django 6.0.7 on 2026-07-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_city_user_date_of_birth_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("employee", "Coach"),
                    ("hr", "Human Resources"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
