# Generated by Django 6.0.7 on 2026-07-23 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("Walking", "Walking"),
                            ("Running", "Running"),
                            ("Strength Training", "Strength Training"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Yoga", "Yoga"),
                            ("HIIT", "HIIT"),
                            ("Sports", "Sports"),
                            ("Other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "workout_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("Light", "Light"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-workout_date", "-created_at"],
            },
        ),
    ]
